---
- name: Get latest url for linux-amd64 release for aws-iam-authenticator
  uri:
    url: "{{ authenticator_url }}"
    return_content: true
    body_format: json
  register: json_response

- name: Download and install aws-iam-authenticator
  get_url:
    url:  "{{ json_response.json | to_json | from_json| json_query(\"assets[?ends_with(name,'linux_amd64')].browser_download_url | [0]\") }}"
    dest: /usr/local/bin/aws-iam-authenticator
    mode: 0555
  become: yes