#!/usr/bin/env ansible-playbook
---
 # This playbook will setup common services required for all newly created hosts.

- hosts: all
  pre_tasks:
  - name:  Get hostname
    block:
    - name: Show inventory_hostname
      debug:
        var: inventory_hostname
    - name: Show ansible_hostname
      debug:
        var: ansible_hostname
  roles:
    - common_baseline
